# Generated by Django 3.2.5 on 2022-04-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieActorTable',
            new_name='MovieActorRelation',
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
    ]
